//! Golden tests for the apply, revert and script commands, and their round trip through the
//! fixture backend.

use outlay::model::Snapshot;
use outlay::model::layout::Layout;
use outlay::xrandr::{Backend, FixtureBackend, command, parse_verbose};

fn fixture(name: &str) -> Snapshot {
    let path = format!(
        "{}/tests/fixtures/xrandr/{name}.txt",
        env!("CARGO_MANIFEST_DIR")
    );
    parse_verbose(&std::fs::read_to_string(path).unwrap()).unwrap()
}

/// The demo with DP-1-3 turned on, HDMI-1-0 one rate up and eDP-1 made primary.
fn edited_demo() -> (Snapshot, Layout) {
    let snap = fixture("demo");
    let (mut layout, _) = Layout::from_snapshot(&snap);
    layout.turn_on(&snap, snap.find("DP-1-3").unwrap()).unwrap();
    layout
        .step_rate(&snap, snap.find("HDMI-1-0").unwrap(), true)
        .unwrap();
    layout.set_primary(snap.find("eDP-1").unwrap()).unwrap();
    (snap, layout)
}

#[test]
fn apply_of_the_unchanged_demo() {
    let snap = fixture("demo");
    let (layout, notes) = Layout::from_snapshot(&snap);
    assert!(notes.is_empty());
    assert!(layout.diff(&snap).is_empty());
    assert_eq!(
        command::command_line(&command::apply_args(&layout, &snap)),
        "xrandr --output HDMI-1-0 --mode 0x1c3 --pos 0x360 --rotate normal --reflect normal \
         --output DP-1-2 --primary --mode 0x1cb --pos 1920x0 --rotate normal --reflect normal \
         --output eDP-1 --mode 0x1cf --pos 2240x1440 --rotate normal --reflect normal \
         --output DP-1-3 --off"
    );
}

#[test]
fn apply_and_copy_of_an_edited_demo() {
    let (snap, layout) = edited_demo();
    let diff: Vec<String> = layout.diff(&snap).iter().map(ToString::to_string).collect();
    assert_eq!(
        diff,
        [
            "HDMI-1-0  rate 59.94 → 60.00",
            "eDP-1  primary",
            "DP-1-3  off → 3840x2160@60.00"
        ]
    );
    assert_eq!(
        command::command_line(&command::apply_args(&layout, &snap)),
        "xrandr --output HDMI-1-0 --mode 0x1c4 --pos 0x360 --rotate normal --reflect normal \
         --output DP-1-2 --mode 0x1cb --pos 1920x0 --rotate normal --reflect normal \
         --output eDP-1 --primary --mode 0x1cf --pos 2240x1440 --rotate normal --reflect normal \
         --output DP-1-3 --mode 0x1d6 --pos 4480x0 --rotate normal --reflect normal"
    );
    assert_eq!(
        command::command_line(&command::portable_args(&layout, &snap)),
        "xrandr --output HDMI-1-0 --mode 1920x1080 --rate 60.00 --pos 0x360 --rotate normal --reflect normal \
         --output DP-1-2 --mode 2560x1440 --rate 143.91 --pos 1920x0 --rotate normal --reflect normal \
         --output eDP-1 --primary --mode 1920x1080 --rate 165.01 --pos 2240x1440 --rotate normal --reflect normal \
         --output DP-1-3 --mode 3840x2160 --rate 60.00 --pos 4480x0 --rotate normal --reflect normal"
    );
}

#[test]
fn revert_of_the_demo() {
    let snap = fixture("demo");
    assert_eq!(
        command::command_line(&command::revert_args(&snap)),
        "xrandr --output HDMI-1-0 --mode 0x1c3 --pos 0x360 --rotate normal --reflect normal --transform none \
         --output DP-1-2 --primary --mode 0x1cb --pos 1920x0 --rotate normal --reflect normal --transform none \
         --output eDP-1 --mode 0x1cf --pos 2240x1440 --rotate normal --reflect normal --transform none \
         --output DP-1-3 --off"
    );
}

#[test]
fn script_of_the_demo() {
    let snap = fixture("demo");
    let (layout, _) = Layout::from_snapshot(&snap);
    assert_eq!(
        command::script(&layout, &snap),
        "#!/bin/sh\n\
         # generated by outlay 0.1.0\n\
         xrandr --output HDMI-1-0 --mode 1920x1080 --rate 59.94 --pos 0x360 --rotate normal \\\n       \
         --output DP-1-2 --primary --mode 2560x1440 --rate 143.91 --pos 1920x0 --rotate normal \\\n       \
         --output eDP-1 --mode 1920x1080 --rate 165.01 --pos 2240x1440 --rotate normal \\\n       \
         --output DP-1-3 --off\n"
    );
}

#[test]
fn scale_in_revert_script_and_reset() {
    let snap = fixture("scaled");
    let (mut layout, _) = Layout::from_snapshot(&snap);
    assert_eq!(
        command::command_line(&command::revert_args(&snap)),
        "xrandr --output eDP-1 --primary --mode 0x1c0 --pos 0x0 --rotate normal --reflect normal \
         --transform 1.5,0,0,0,1.5,0,0,0,1 --filter bilinear \
         --output HDMI-1 --mode 0x1c7 --pos 2880x0 --rotate normal --reflect normal --transform none"
    );
    let script = command::script(&layout, &snap);
    assert!(
        script.contains("xrandr --output eDP-1 --primary --mode 1920x1080 --rate 60.00 --pos 0x0 --rotate normal --scale 1.5x1.5 \\\n"),
        "{script}"
    );
    assert!(
        script.ends_with("       --output DP-1 --off\n"),
        "every known output appears:\n{script}"
    );

    layout.reset_scale(snap.find("eDP-1").unwrap()).unwrap();
    let diff: Vec<String> = layout.diff(&snap).iter().map(ToString::to_string).collect();
    assert_eq!(
        diff,
        ["eDP-1  scale ×1.5 → ×1", "HDMI-1  pos 2880,0 → 1920,0"]
    );
    assert_eq!(
        command::command_line(&command::apply_args(&layout, &snap)),
        "xrandr --output eDP-1 --primary --mode 0x1c0 --pos 0x0 --rotate normal --reflect normal --transform none \
         --output HDMI-1 --mode 0x1c7 --pos 1920x0 --rotate normal --reflect normal"
    );
}

#[test]
fn panning_outputs_are_left_alone() {
    let snap = fixture("panning");
    let (layout, _) = Layout::from_snapshot(&snap);
    assert_eq!(
        command::command_line(&command::apply_args(&layout, &snap)),
        "xrandr --output HDMI-1 --mode 0x1c0 --pos 1920x0 --rotate normal --reflect normal"
    );
    assert!(!command::revert_args(&snap).contains(&"eDP-1".to_owned()));
}

#[test]
fn no_primary_is_explicit() {
    let snap = fixture("unknown-connection");
    let (mut layout, _) = Layout::from_snapshot(&snap);
    let lvds = snap.find("LVDS-1").unwrap();
    layout.outputs[lvds].primary = false;
    assert_eq!(
        command::apply_args(&layout, &snap).last().unwrap(),
        "--noprimary"
    );
    let mut live = snap.clone();
    live.outputs[lvds].primary = false;
    assert_eq!(command::revert_args(&live).last().unwrap(), "--noprimary");
}

#[test]
fn apply_then_revert_round_trips_through_the_fixture_backend() {
    let (snap, layout) = edited_demo();
    let backend = FixtureBackend::new(snap.clone());
    let outcome = backend.apply(&command::apply_args(&layout, &snap)).unwrap();
    assert!(
        outcome.success && outcome.stderr.is_empty(),
        "{}",
        outcome.stderr
    );

    // The applied state reads back as the same layout.
    let applied = backend.query().unwrap();
    let reread = Layout::inferred(&applied);
    for i in layout.enabled() {
        assert_eq!(reread.rect(i), layout.rect(i), "{}", layout.names[i]);
        assert_eq!(reread.outputs[i].mode, layout.outputs[i].mode);
        assert_eq!(reread.outputs[i].primary, layout.outputs[i].primary);
    }
    assert!(layout.diff(&applied).is_empty());

    // The revert built before applying restores the snapshot exactly.
    let outcome = backend.apply(&command::revert_args(&snap)).unwrap();
    assert!(outcome.success, "{}", outcome.stderr);
    assert_eq!(backend.query().unwrap(), snap);
}
