//! Golden tests for the apply, revert and script commands, and their round trip through the
//! fixture backend.

use outlay::backend::{Backend, FixtureBackend, Plan, PrimaryRule};
use outlay::model::layout::Layout;
use outlay::model::{Reflection, Rotation, Snapshot};
use outlay::wayland::capture::parse as parse_capture;
use outlay::xrandr::command::argv_to_plan;
use outlay::xrandr::{command, parse_verbose};

/// The xrandr arguments of the apply of `layout`.
fn apply_args(layout: &Layout, snap: &Snapshot) -> Vec<String> {
    command::argv(&Plan::pending(layout, snap))
}

/// The same apply as `y` copies it.
fn portable_args(layout: &Layout, snap: &Snapshot) -> Vec<String> {
    command::portable_argv(&Plan::pending(layout, snap))
}

/// The xrandr arguments that restore `live`.
fn revert_args(live: &Snapshot) -> Vec<String> {
    command::argv(&Plan::restore(live))
}

fn fixture(name: &str) -> Snapshot {
    let path = format!(
        "{}/tests/fixtures/xrandr/{name}.txt",
        env!("CARGO_MANIFEST_DIR")
    );
    parse_verbose(&std::fs::read_to_string(path).unwrap()).unwrap()
}

fn wayland_fixture(name: &str) -> Snapshot {
    let path = format!(
        "{}/tests/fixtures/wayland/{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    parse_capture(&std::fs::read_to_string(path).unwrap()).unwrap()
}

/// The demo with DP-1-3 turned on, HDMI-1-0 one rate up and eDP-1 made primary.
fn edited_demo() -> (Snapshot, Layout) {
    let snap = fixture("demo");
    let (mut layout, _) = Layout::from_snapshot(&snap);
    layout.turn_on(&snap, snap.find("DP-1-3").unwrap()).unwrap();
    layout
        .step_rate(&snap, snap.find("HDMI-1-0").unwrap(), true)
        .unwrap();
    layout.set_primary(snap.find("eDP-1").unwrap()).unwrap();
    (snap, layout)
}

#[test]
fn apply_of_the_unchanged_demo() {
    let snap = fixture("demo");
    let (layout, notes) = Layout::from_snapshot(&snap);
    assert!(notes.is_empty());
    assert!(layout.diff(&snap).is_empty());
    assert_eq!(
        command::command_line(&apply_args(&layout, &snap)),
        "xrandr --output HDMI-1-0 --mode 0x1c3 --pos 0x360 --rotate normal --reflect normal \
         --output DP-1-2 --primary --mode 0x1cb --pos 1920x0 --rotate normal --reflect normal \
         --output eDP-1 --mode 0x1cf --pos 2240x1440 --rotate normal --reflect normal \
         --output DP-1-3 --off"
    );
}

#[test]
fn apply_and_copy_of_an_edited_demo() {
    let (snap, layout) = edited_demo();
    let diff: Vec<String> = layout.diff(&snap).iter().map(ToString::to_string).collect();
    assert_eq!(
        diff,
        [
            "HDMI-1-0  rate 59.94 → 60.00",
            "eDP-1  primary",
            "DP-1-3  off → 3840x2160@60.00"
        ]
    );
    assert_eq!(
        command::command_line(&apply_args(&layout, &snap)),
        "xrandr --output HDMI-1-0 --mode 0x1c4 --pos 0x360 --rotate normal --reflect normal \
         --output DP-1-2 --mode 0x1cb --pos 1920x0 --rotate normal --reflect normal \
         --output eDP-1 --primary --mode 0x1cf --pos 2240x1440 --rotate normal --reflect normal \
         --output DP-1-3 --mode 0x1d6 --pos 4480x0 --rotate normal --reflect normal"
    );
    assert_eq!(
        command::command_line(&portable_args(&layout, &snap)),
        "xrandr --output HDMI-1-0 --mode 1920x1080 --rate 60.00 --pos 0x360 --rotate normal --reflect normal \
         --output DP-1-2 --mode 2560x1440 --rate 143.91 --pos 1920x0 --rotate normal --reflect normal \
         --output eDP-1 --primary --mode 1920x1080 --rate 165.01 --pos 2240x1440 --rotate normal --reflect normal \
         --output DP-1-3 --mode 3840x2160 --rate 60.00 --pos 4480x0 --rotate normal --reflect normal"
    );
}

#[test]
fn revert_of_the_demo() {
    let snap = fixture("demo");
    assert_eq!(
        command::command_line(&revert_args(&snap)),
        "xrandr --output HDMI-1-0 --mode 0x1c3 --pos 0x360 --rotate normal --reflect normal --transform none \
         --output DP-1-2 --primary --mode 0x1cb --pos 1920x0 --rotate normal --reflect normal --transform none \
         --output eDP-1 --mode 0x1cf --pos 2240x1440 --rotate normal --reflect normal --transform none \
         --output DP-1-3 --off"
    );
}

#[test]
fn script_of_the_demo() {
    let snap = fixture("demo");
    let (layout, _) = Layout::from_snapshot(&snap);
    assert_eq!(
        command::script(&layout),
        concat!(
            "#!/bin/sh\n# generated by outlay ",
            env!("CARGO_PKG_VERSION"),
            "\n\
             xrandr --output HDMI-1-0 --mode 1920x1080 --rate 59.94 --pos 0x360 --rotate normal \\\n       \
             --output DP-1-2 --primary --mode 2560x1440 --rate 143.91 --pos 1920x0 --rotate normal \\\n       \
             --output eDP-1 --mode 1920x1080 --rate 165.01 --pos 2240x1440 --rotate normal \\\n       \
             --output DP-1-3 --off\n"
        )
    );
}

#[test]
fn scale_in_revert_script_and_reset() {
    let snap = fixture("scaled");
    let (mut layout, _) = Layout::from_snapshot(&snap);
    assert_eq!(
        command::command_line(&revert_args(&snap)),
        "xrandr --output eDP-1 --primary --mode 0x1c0 --pos 0x0 --rotate normal --reflect normal \
         --transform 1.5,0,0,0,1.5,0,0,0,1 --filter bilinear \
         --output HDMI-1 --mode 0x1c7 --pos 2880x0 --rotate normal --reflect normal --transform none"
    );
    let script = command::script(&layout);
    assert!(
        script.contains("xrandr --output eDP-1 --primary --mode 1920x1080 --rate 60.00 --pos 0x0 --rotate normal --scale 1.5x1.5 \\\n"),
        "{script}"
    );
    assert!(
        script.ends_with("       --output DP-1 --off\n"),
        "every known output appears:\n{script}"
    );

    layout.reset_scale(snap.find("eDP-1").unwrap()).unwrap();
    let diff: Vec<String> = layout.diff(&snap).iter().map(ToString::to_string).collect();
    assert_eq!(
        diff,
        ["eDP-1  scale ×1.5 → ×1", "HDMI-1  pos 2880,0 → 1920,0"]
    );
    assert_eq!(
        command::command_line(&apply_args(&layout, &snap)),
        "xrandr --output eDP-1 --primary --mode 0x1c0 --pos 0x0 --rotate normal --reflect normal --transform none \
         --output HDMI-1 --mode 0x1c7 --pos 1920x0 --rotate normal --reflect normal"
    );
}

#[test]
fn panning_outputs_are_left_alone() {
    let snap = fixture("panning");
    let (layout, _) = Layout::from_snapshot(&snap);
    assert_eq!(
        command::command_line(&apply_args(&layout, &snap)),
        "xrandr --output HDMI-1 --mode 0x1c0 --pos 1920x0 --rotate normal --reflect normal"
    );
    assert!(!revert_args(&snap).contains(&"eDP-1".to_owned()));
    // eDP-1 is primary and locked: it is left out, but it still counts, so no --noprimary.
    let plan = Plan::pending(&layout, &snap);
    assert!(plan.find("eDP-1").is_none());
    assert_eq!(plan.primary, PrimaryRule::Keep);
}

#[test]
fn no_primary_is_explicit() {
    let snap = fixture("unknown-connection");
    let (mut layout, _) = Layout::from_snapshot(&snap);
    let lvds = snap.find("LVDS-1").unwrap();
    layout.outputs[lvds].primary = false;
    assert_eq!(apply_args(&layout, &snap).last().unwrap(), "--noprimary");
    let mut live = snap.clone();
    live.outputs[lvds].primary = false;
    assert_eq!(revert_args(&live).last().unwrap(), "--noprimary");
}

#[test]
fn apply_then_revert_round_trips_through_the_fixture_backend() {
    let (snap, layout) = edited_demo();
    let backend = FixtureBackend::new(snap.clone());
    let outcome = backend.apply(&Plan::pending(&layout, &snap)).unwrap();
    assert!(
        outcome.success && outcome.stderr.is_empty(),
        "{}",
        outcome.stderr
    );

    // The applied state reads back as the same layout.
    let applied = backend.query().unwrap();
    let reread = Layout::inferred(&applied);
    for i in layout.enabled() {
        assert_eq!(reread.rect(i), layout.rect(i), "{}", layout.names[i]);
        assert_eq!(reread.outputs[i].mode, layout.outputs[i].mode);
        assert_eq!(reread.outputs[i].primary, layout.outputs[i].primary);
    }
    assert!(layout.diff(&applied).is_empty());

    // The revert built before applying restores the snapshot exactly.
    let outcome = backend.apply(&Plan::restore(&snap)).unwrap();
    assert!(outcome.success, "{}", outcome.stderr);
    assert_eq!(backend.query().unwrap(), snap);
}

#[test]
fn plans_round_trip_through_xid_arguments() {
    let (snap, layout) = edited_demo();
    let mut cases = vec![(snap.clone(), layout)];
    for name in [
        "demo",
        "scaled",
        "panning",
        "mirror",
        "dock-mst-3",
        "unknown-connection",
    ] {
        let snap = fixture(name);
        let (mut layout, _) = Layout::from_snapshot(&snap);
        cases.push((snap.clone(), layout.clone()));
        if layout.reset_scale(0).is_ok() {
            cases.push((snap.clone(), layout));
        }
    }
    for (snap, layout) in cases {
        let plan = Plan::pending(&layout, &snap);
        let argv = command::argv(&plan);
        assert_eq!(argv_to_plan(&snap, &argv), Ok(plan), "{argv:?}");
        let restore = Plan::restore(&snap);
        let back = argv_to_plan(&snap, &command::argv(&restore)).unwrap();
        assert_eq!(back.outputs, restore.outputs);
        assert_eq!(back.primary, restore.primary);
    }
}

#[test]
fn a_scale_is_written_only_where_it_changes() {
    // Unchanged, eDP-1 keeps its ×1.5 and its filter: nothing about the scale is written.
    let snap = fixture("scaled");
    let (mut layout, _) = Layout::from_snapshot(&snap);
    assert_eq!(
        command::command_line(&apply_args(&layout, &snap)),
        "xrandr --output eDP-1 --primary --mode 0x1c0 --pos 0x0 --rotate normal --reflect normal \
         --output HDMI-1 --mode 0x1c7 --pos 2880x0 --rotate normal --reflect normal"
    );

    let edp = snap.find("eDP-1").unwrap();
    layout.set_scale(edp, 1.25).unwrap();
    let diff: Vec<String> = layout.diff(&snap).iter().map(ToString::to_string).collect();
    assert_eq!(
        diff,
        ["eDP-1  scale ×1.5 → ×1.25", "HDMI-1  pos 2880,0 → 2400,0"]
    );
    assert_eq!(
        command::command_line(&apply_args(&layout, &snap)),
        "xrandr --output eDP-1 --primary --mode 0x1c0 --pos 0x0 --rotate normal --reflect normal \
         --scale 1.25x1.25 \
         --output HDMI-1 --mode 0x1c7 --pos 2400x0 --rotate normal --reflect normal"
    );
    assert!(
        portable_args(&layout, &snap).contains(&"1.25x1.25".to_owned()),
        "y copies it too"
    );

    // Applied, it reads back as asked; from there, ×1.5 is a change again.
    let backend = FixtureBackend::new(snap.clone());
    let outcome = backend.apply(&Plan::pending(&layout, &snap)).unwrap();
    assert!(outcome.success, "{}", outcome.stderr);
    let live = backend.query().unwrap();
    assert!(
        layout.mismatches(&live).is_empty(),
        "{:?}",
        layout.mismatches(&live)
    );
    assert!(layout.diff(&live).is_empty());
    let (mut again, _) = Layout::from_snapshot(&live);
    again.set_scale(edp, 1.5).unwrap();
    let diff: Vec<String> = again.diff(&live).iter().map(ToString::to_string).collect();
    assert_eq!(
        diff,
        ["eDP-1  scale ×1.25 → ×1.5", "HDMI-1  pos 2400,0 → 2880,0"]
    );

    // On the demo, only the output that changes gets --scale; centred below DP-1-2, it re-flows.
    let snap = fixture("demo");
    let (mut layout, _) = Layout::from_snapshot(&snap);
    layout.set_scale(snap.find("eDP-1").unwrap(), 1.5).unwrap();
    let line = command::command_line(&apply_args(&layout, &snap));
    assert_eq!(line.matches("--scale").count(), 1, "{line}");
    assert!(
        line.contains("--output eDP-1 --mode 0x1cf --pos 1760x1440 --rotate normal --reflect normal --scale 1.5x1.5"),
        "{line}"
    );
    assert!(!line.contains("--transform"), "{line}");
}

/// `layout` with output `name`'s orientation as asked; the rest as it is.
fn oriented(layout: &Layout, name: &str, rotation: Rotation, reflection: Reflection) -> Layout {
    let mut layout = layout.clone();
    let i = layout.names.iter().position(|n| n == name).unwrap();
    layout.outputs[i].rotation = rotation;
    layout.outputs[i].reflection = reflection;
    layout
}

#[test]
fn verification_compares_the_orientation() {
    // A turn by 180° and a reflection keep the rectangle, so only the orientation tells.
    let x11 = fixture("demo");
    let wayland = wayland_fixture("demo");
    let cases = [
        (
            &x11,
            Rotation::Inverted,
            Reflection::Normal,
            "eDP-1 is normal instead of inverted.",
        ),
        (
            &x11,
            Rotation::Normal,
            Reflection::X,
            "eDP-1 is normal instead of normal, reflect x.",
        ),
        (
            &wayland,
            Rotation::Inverted,
            Reflection::Normal,
            "eDP-1 is normal instead of 180 (inverted).",
        ),
        (
            &wayland,
            Rotation::Normal,
            Reflection::X,
            "eDP-1 is normal instead of flipped.",
        ),
    ];
    for (snap, rotation, reflection, text) in cases {
        let (layout, _) = Layout::from_snapshot(snap);
        assert!(layout.mismatches(snap).is_empty());
        let asked = oriented(&layout, "eDP-1", rotation, reflection);
        assert_eq!(asked.mismatches(snap), [text]);
    }
}

#[test]
fn verification_accepts_the_same_picture_named_another_way() {
    // Wayland has no reflection in y: `reflect xy` is sent as `180`, `reflect y` as
    // `flipped-180`, and each reads back that way.
    let snap = wayland_fixture("demo");
    let (layout, _) = Layout::from_snapshot(&snap);
    for (asked, read_back) in [
        (Reflection::XY, (Rotation::Inverted, Reflection::Normal)),
        (Reflection::Y, (Rotation::Inverted, Reflection::X)),
    ] {
        let want = oriented(&layout, "eDP-1", Rotation::Normal, asked);
        let mut live = snap.clone();
        let i = live.find("eDP-1").unwrap();
        let active = live.outputs[i].active.as_mut().unwrap();
        (active.rotation, active.reflection) = read_back;
        assert!(
            want.mismatches(&live).is_empty(),
            "{:?}",
            want.mismatches(&live)
        );
        let normal = oriented(&layout, "eDP-1", Rotation::Normal, Reflection::Normal);
        assert_eq!(normal.mismatches(&live).len(), 1, "{asked:?}");
    }
}
