//! kanshi profiles: the config kanshi reads (`$XDG_CONFIG_HOME/kanshi/config`), read into the
//! neutral [`Profile`] and written back one profile block at a time.
//!
//! Reading follows kanshi 1.9.0: the scfg syntax as libscfg parses it, `include` with shell
//! expansion, global `output` defaults and `$alias`es (`config.c`), and how a profile picks its
//! mode (`main.c`). Reading is lenient: what kanshi would reject becomes a warning. `exec` and
//! `...output` stay in the file; outlay neither runs nor matches them, and says so.
//!
//! Saving rewrites one profile's `output` lines and its `# generated by outlay` comment, or
//! appends a new block. Every other byte stays, comments and `exec` lines inside the block too.

use std::io;
use std::ops::Range;
use std::path::{Path, PathBuf};

use crate::model::geometry::Point;
use crate::model::layout::Layout;
use crate::model::profile::{Entry, ModeRequest, Profile, Target, description, glob_match};
use crate::model::{Reflection, Rotation, Scaling, Snapshot};

use super::capture::mode_millihertz;
use super::{built_in, parse_transform, transform_name};

/// How deep `include`s may nest.
const MAX_INCLUDE_DEPTH: usize = 8;

/// The indentation of a new block's lines.
const INDENT: &str = "    ";

// --- scfg ---------------------------------------------------------------------------------------

/// One scfg directive: a name, its parameters, and the block after them, if any.
#[derive(Clone, Debug, PartialEq)]
struct Directive {
    name: String,
    params: Vec<String>,
    children: Option<Vec<Directive>>,
    /// From the start of its first line to just past its last one (the closing brace's).
    lines: Range<usize>,
    /// Where the directive itself starts.
    start: usize,
    /// Just past its `{`, for a directive with a block.
    open: Option<usize>,
    /// Its first line, from 1.
    line: usize,
}

/// libscfg's parser, keeping where each directive is. Problems become messages, and parsing
/// goes on.
struct Parser<'a> {
    text: &'a str,
    pos: usize,
    line: usize,
    problems: Vec<String>,
}

impl<'a> Parser<'a> {
    fn new(text: &'a str) -> Self {
        Self {
            text,
            pos: 0,
            line: 1,
            problems: Vec::new(),
        }
    }

    fn peek(&self) -> Option<char> {
        self.text[self.pos..].chars().next()
    }

    fn bump(&mut self) -> Option<char> {
        let c = self.peek()?;
        self.pos += c.len_utf8();
        if c == '\n' {
            self.line += 1;
        }
        Some(c)
    }

    fn blanks(&mut self) {
        while matches!(self.peek(), Some(' ' | '\t')) {
            self.bump();
        }
    }

    fn problem(&mut self, line: usize, text: impl AsRef<str>) {
        self.problems
            .push(format!("line {line}: {}", text.as_ref()));
    }

    /// Directives up to the end of the text, or up to the `}` that closes a nested block.
    fn block(&mut self, nested: bool) -> Vec<Directive> {
        let mut out = Vec::new();
        loop {
            self.blanks();
            match self.peek() {
                None => {
                    if nested {
                        self.problem(self.line, "a block has no closing '}'");
                    }
                    return out;
                }
                Some('\n') => {
                    self.bump();
                }
                Some('#') => while !matches!(self.bump(), None | Some('\n')) {},
                Some('}') if nested => {
                    self.bump();
                    return out;
                }
                Some('}') => {
                    self.problem(self.line, "unexpected '}'");
                    self.bump();
                }
                Some(_) => out.push(self.directive()),
            }
        }
    }

    fn directive(&mut self) -> Directive {
        let start = self.pos;
        let line = self.line;
        let line_start = self.text[..start].rfind('\n').map_or(0, |k| k + 1);
        let name = self.word();
        let mut params = Vec::new();
        let mut children = None;
        let mut open = None;
        loop {
            self.blanks();
            match self.peek() {
                None => break,
                Some('\n') => {
                    self.bump();
                    break;
                }
                Some('{') => {
                    self.bump();
                    open = Some(self.pos);
                    children = Some(self.block(true));
                    self.blanks();
                    if self.peek() == Some('\n') {
                        self.bump();
                    }
                    break;
                }
                Some('}') => {
                    self.problem(self.line, "unexpected '}' after a directive");
                    break;
                }
                Some(_) => params.push(self.word()),
            }
        }
        Directive {
            name,
            params,
            children,
            lines: line_start..self.pos,
            start,
            open,
            line,
        }
    }

    /// A bare word, a `"double-quoted"` one with backslash escapes, or a `'single-quoted'` one.
    fn word(&mut self) -> String {
        let line = self.line;
        let mut word = String::new();
        if let Some(quote @ ('"' | '\'')) = self.peek() {
            self.bump();
            loop {
                match self.peek() {
                    None | Some('\n') => {
                        self.problem(line, "a quoted word is not closed");
                        break;
                    }
                    Some(c) if c == quote => {
                        self.bump();
                        break;
                    }
                    Some('\\') if quote == '"' => {
                        self.bump();
                        if let Some(c) = self.peek().filter(|&c| c != '\n') {
                            self.bump();
                            word.push(c);
                        }
                    }
                    Some(c) => {
                        self.bump();
                        word.push(c);
                    }
                }
            }
            return word;
        }
        loop {
            match self.peek() {
                None | Some(' ' | '\t' | '\n') => break,
                Some(c @ ('{' | '}')) => {
                    if !word.is_empty() {
                        self.problem(line, format!("'{c}' needs a space before it"));
                    }
                    break;
                }
                Some('\\') => {
                    self.bump();
                    if let Some(c) = self.peek().filter(|&c| c != '\n') {
                        self.bump();
                        word.push(c);
                    }
                }
                Some(c) => {
                    if matches!(c, '"' | '\'') {
                        self.problem(line, format!("unexpected {c} inside a word"));
                    }
                    self.bump();
                    word.push(c);
                }
            }
        }
        word
    }
}

/// A word as scfg reads it back: bare when it can be, else double-quoted.
fn quote(word: &str) -> String {
    let special = |c: char| c.is_whitespace() || matches!(c, '"' | '\'' | '{' | '}' | '\\' | '#');
    if !word.is_empty() && !word.contains(special) {
        return word.to_owned();
    }
    let mut out = String::from("\"");
    for c in word.chars() {
        if matches!(c, '"' | '\\') {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

// --- What kanshi reads ----------------------------------------------------------------------------

/// What a kanshi config holds, as far as outlay reads it.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Config {
    /// Every profile, in the order kanshi tries them.
    pub profiles: Vec<Block>,
    /// Every file read, with its text: the config first, then the files it includes.
    pub files: Vec<(PathBuf, String)>,
    /// Problems with the config as a whole: kanshi rejects a config with any of them.
    pub problems: Vec<String>,
}

/// One `profile` block.
#[derive(Clone, Debug, PartialEq)]
pub struct Block {
    /// The profile's name; kanshi calls an unnamed one `<anonymous profile N>`.
    pub name: String,
    pub anonymous: bool,
    /// Which of [`Config::files`] holds it.
    pub file: usize,
    /// The block in that file, from the start of its `profile` line to the end of the line with
    /// its closing brace.
    pub lines: Range<usize>,
    /// Where the `profile` directive starts.
    pub start: usize,
    /// Just past the block's `{`.
    pub open: usize,
    pub profile: Profile,
    /// The block's `output` directives, one per entry of `profile`.
    pub outputs: Vec<Written>,
}

/// An `output` directive in a profile block, as the file has it.
#[derive(Clone, Debug, PartialEq)]
pub struct Written {
    /// The criteria as written: a name, a description, `*`, or an `$alias`.
    pub criteria: String,
    pub lines: Range<usize>,
    pub start: usize,
    /// `adaptive_sync`, which outlay keeps as it is.
    pub adaptive_sync: Option<bool>,
}

/// The settings of one `output` directive, before global defaults fill in what it leaves out.
#[derive(Clone, Debug, Default, PartialEq)]
struct Settings {
    criteria: String,
    enabled: Option<bool>,
    mode: Option<(ModeRequest, Option<f64>)>,
    position: Option<Point>,
    scale: Option<f64>,
    transform: Option<(Rotation, Reflection)>,
    adaptive_sync: Option<bool>,
    alias: Option<String>,
}

/// `WxH[@R[Hz]]`, as kanshi's `parse_mode` reads it. A rate of 0 is no rate.
fn parse_mode(text: &str) -> Option<(i32, i32, Option<f64>)> {
    let (width, rest) = text.split_once('x')?;
    let (height, rate) = match rest.split_once('@') {
        Some((h, r)) => (h, Some(r)),
        None => (rest, None),
    };
    let (width, height) = (width.parse().ok()?, height.parse().ok()?);
    let rate = match rate {
        Some(r) => {
            let hz: f64 = r.strip_suffix("Hz").unwrap_or(r).parse().ok()?;
            (hz.is_finite() && hz >= 0.0).then_some(hz)?
        }
        None => 0.0,
    };
    Some((width, height, (rate > 0.0).then_some(rate)))
}

impl Settings {
    /// Reads one output directive (`mode`, `scale` …) from its name and the words after it, as
    /// kanshi's `parse_profile_output_param` does; returns how many of those words it took.
    fn read(&mut self, name: &str, rest: &[String], problems: &mut Vec<String>) -> usize {
        let bad = |what: &str, value: &str| format!("{value:?} is not a valid {what}; ignored.");
        match name {
            "enable" => {
                self.enabled = Some(true);
                return 0;
            }
            "disable" => {
                self.enabled = Some(false);
                return 0;
            }
            _ => {}
        }
        let Some(value) = rest.first() else {
            problems.push(format!("{name} needs a value."));
            return 0;
        };
        match name {
            "mode" if value == "preferred" => self.mode = Some((ModeRequest::Preferred, None)),
            "mode" => {
                let custom = value == "--custom";
                let text = if custom { rest.get(1) } else { Some(value) };
                let Some(text) = text else {
                    problems.push("mode --custom needs a mode.".to_owned());
                    return 1;
                };
                match parse_mode(text) {
                    Some((width, height, rate)) => {
                        let request = if custom {
                            ModeRequest::Custom { width, height }
                        } else {
                            ModeRequest::Size { width, height }
                        };
                        self.mode = Some((request, rate));
                    }
                    None => problems.push(bad("mode", text)),
                }
                return if custom { 2 } else { 1 };
            }
            "position" => {
                let point = value
                    .split_once(',')
                    .and_then(|(x, y)| Some(Point::new(x.parse().ok()?, y.parse().ok()?)));
                match point {
                    Some(p) => self.position = Some(p),
                    None => problems.push(bad("position", value)),
                }
            }
            "scale" => match value.parse::<f64>() {
                Ok(s) if s.is_finite() && s > 0.0 => self.scale = Some(s),
                _ => problems.push(bad("scale", value)),
            },
            "transform" => match parse_transform(value) {
                Some(t) => self.transform = Some(t),
                None => problems.push(bad("transform", value)),
            },
            "adaptive_sync" => match value.as_str() {
                "on" => self.adaptive_sync = Some(true),
                "off" => self.adaptive_sync = Some(false),
                _ => problems.push(bad("adaptive_sync", value)),
            },
            "alias" if value.starts_with('$') => self.alias = Some(value.clone()),
            "alias" => problems.push(bad("alias", value)),
            _ => {
                problems.push(format!("Unknown output directive {name}; ignored."));
                return 0;
            }
        }
        1
    }

    /// The settings of an `output` directive, inline or in a block.
    fn of(d: &Directive, problems: &mut Vec<String>) -> Self {
        let mut settings = Settings {
            criteria: d.params.first().cloned().unwrap_or_default(),
            ..Settings::default()
        };
        let mut found = Vec::new();
        if d.params.is_empty() {
            found.push(format!("{} needs criteria.", d.name));
        }
        let mut k = 1;
        while k < d.params.len() {
            k += 1 + settings.read(&d.params[k], &d.params[k + 1..], &mut found);
        }
        for child in d.children.iter().flatten() {
            let used = settings.read(&child.name, &child.params, &mut found);
            if used != child.params.len() {
                found.push(format!("only one directive per line in {}.", d.name));
            }
        }
        problems.extend(found.into_iter().map(|p| format!("line {}: {p}", d.line)));
        settings
    }

    /// What a global default sets and this leaves out.
    fn fill_from(&mut self, default: &Settings) {
        self.enabled = self.enabled.or(default.enabled);
        if self.mode.is_none() {
            self.mode.clone_from(&default.mode);
        }
        self.position = self.position.or(default.position);
        self.scale = self.scale.or(default.scale);
        self.transform = self.transform.or(default.transform);
        self.adaptive_sync = self.adaptive_sync.or(default.adaptive_sync);
    }

    /// The neutral entry. Criteria with a space or a glob character match descriptions; kanshi
    /// compares them with names too, but no output name has those.
    fn entry(&self) -> Entry {
        let target = match self.criteria.as_str() {
            "*" => Target::Any,
            c if c.contains(|ch: char| ch.is_whitespace() || matches!(ch, '*' | '?' | '[')) => {
                Target::Description(c.to_owned())
            }
            c => Target::Name(c.to_owned()),
        };
        let (mode, rate) = match &self.mode {
            Some((mode, rate)) => (Some(mode.clone()), *rate),
            None => (None, None),
        };
        Entry {
            target,
            off: self.enabled == Some(false),
            keep_off: self.enabled.is_none(),
            mode,
            rate,
            pos: self.position,
            rotation: self.transform.map(|(r, _)| r),
            reflection: self.transform.map(|(_, f)| f),
            scaling: self.scale.map(Scaling::Logical),
            filter: None,
            relative: None,
        }
    }
}

/// A profile block as read, before defaults and aliases are resolved.
struct RawBlock {
    name: Option<String>,
    file: usize,
    directive: Directive,
    outputs: Vec<(Settings, Written)>,
    execs: usize,
    any_number: usize,
    problems: Vec<String>,
}

#[derive(Default)]
struct Reader {
    files: Vec<(PathBuf, String)>,
    problems: Vec<String>,
    blocks: Vec<RawBlock>,
    defaults: Vec<Settings>,
}

/// The file name, for messages.
fn short(path: &Path) -> String {
    path.file_name().map_or_else(
        || path.display().to_string(),
        |n| n.to_string_lossy().into_owned(),
    )
}

/// The paths an `include` names, expanded as `wordexp` does the common cases: `~`, `$VAR` and
/// `${VAR}`, and globs in the file name. A relative path is taken from the including file's
/// directory.
fn expand(word: &str, from: &Path, home: Option<&Path>) -> Result<Vec<PathBuf>, String> {
    let mut text = String::new();
    let mut rest = word;
    if let Some(after) = rest.strip_prefix('~')
        && (after.is_empty() || after.starts_with('/'))
    {
        let home = home.ok_or("there is no home directory")?;
        text.push_str(&home.to_string_lossy());
        rest = after;
    }
    while let Some(k) = rest.find('$') {
        text.push_str(&rest[..k]);
        let after = &rest[k + 1..];
        let (name, next) = match after.strip_prefix('{') {
            Some(inner) => {
                let end = inner.find('}').ok_or("a ${ has no closing }")?;
                (&inner[..end], &inner[end + 1..])
            }
            None => {
                let end = after
                    .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
                    .unwrap_or(after.len());
                (&after[..end], &after[end..])
            }
        };
        let value = std::env::var(name).map_err(|_| format!("${name} is not set"))?;
        text.push_str(&value);
        rest = next;
    }
    text.push_str(rest);
    let mut path = PathBuf::from(text);
    if path.is_relative() {
        path = from.parent().unwrap_or(Path::new("")).join(path);
    }
    let pattern = path
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    if !pattern.contains(['*', '?', '[']) {
        return Ok(vec![path]);
    }
    let dir = path.parent().unwrap_or(Path::new("/"));
    let mut found: Vec<PathBuf> = std::fs::read_dir(dir)
        .map_err(|err| format!("could not read {}: {err}", dir.display()))?
        .filter_map(Result::ok)
        .filter(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            !name.starts_with('.') && glob_match(&pattern, &name)
        })
        .map(|e| e.path())
        .collect();
    found.sort();
    // wordexp leaves a pattern that matches nothing as it is.
    if found.is_empty() {
        found.push(path);
    }
    Ok(found)
}

impl Reader {
    fn file(&mut self, path: PathBuf, text: String, depth: usize) {
        let index = self.files.len();
        let mut parser = Parser::new(&text);
        let directives = parser.block(false);
        let shown = short(&path);
        let mut problems: Vec<String> = parser
            .problems
            .into_iter()
            .map(|p| format!("{shown}, {p}"))
            .collect();
        self.files.push((path.clone(), text));
        for d in directives {
            match d.name.as_str() {
                "profile" => self.profile(index, d, &shown),
                "output" => {
                    let mut found = Vec::new();
                    let settings = Settings::of(&d, &mut found);
                    problems.extend(found.into_iter().map(|p| format!("{shown}, {p}")));
                    if settings.criteria == "*" || settings.criteria.starts_with('$') {
                        problems.push(format!(
                            "{shown}, line {}: a global output cannot be {}.",
                            d.line, settings.criteria
                        ));
                    } else {
                        self.defaults.push(settings);
                    }
                }
                "include" => {
                    self.problems.append(&mut problems);
                    self.include(&path, &d, depth);
                }
                other => problems.push(format!(
                    "{shown}, line {}: unknown directive {other}.",
                    d.line
                )),
            }
        }
        self.problems.append(&mut problems);
    }

    fn include(&mut self, from: &Path, d: &Directive, depth: usize) {
        let shown = short(from);
        let [word] = d.params.as_slice() else {
            self.problems
                .push(format!("{shown}, line {}: include takes one path.", d.line));
            return;
        };
        if depth >= MAX_INCLUDE_DEPTH {
            self.problems
                .push(format!("{shown}, line {}: includes nest too deep.", d.line));
            return;
        }
        let paths = match expand(word, from, dirs::home_dir().as_deref()) {
            Ok(paths) => paths,
            Err(why) => {
                self.problems.push(format!(
                    "{shown}, line {}: cannot include {word}: {why}.",
                    d.line
                ));
                return;
            }
        };
        for path in paths {
            if self.files.iter().any(|(p, _)| *p == path) {
                self.problems.push(format!(
                    "{shown}, line {}: {} is included again; read once.",
                    d.line,
                    path.display()
                ));
                continue;
            }
            match std::fs::read_to_string(&path) {
                Ok(text) => self.file(path, text, depth + 1),
                Err(err) => self.problems.push(format!(
                    "{shown}, line {}: could not read {}: {err}.",
                    d.line,
                    path.display()
                )),
            }
        }
    }

    fn profile(&mut self, file: usize, d: Directive, shown: &str) {
        let mut raw = RawBlock {
            name: d.params.first().cloned(),
            file,
            directive: d.clone(),
            outputs: Vec::new(),
            execs: 0,
            any_number: 0,
            problems: Vec::new(),
        };
        if d.params.len() > 1 {
            raw.problems.push(format!(
                "{shown}, line {}: a profile takes one name.",
                d.line
            ));
        }
        if d.children.is_none() {
            raw.problems.push(format!(
                "{shown}, line {}: the profile has no {{ block }}.",
                d.line
            ));
        }
        for child in d.children.iter().flatten() {
            match child.name.as_str() {
                "output" => {
                    let mut found = Vec::new();
                    let settings = Settings::of(child, &mut found);
                    raw.problems
                        .extend(found.into_iter().map(|p| format!("{shown}, {p}")));
                    let written = Written {
                        criteria: settings.criteria.clone(),
                        lines: child.lines.clone(),
                        start: child.start,
                        adaptive_sync: settings.adaptive_sync,
                    };
                    raw.outputs.push((settings, written));
                }
                "...output" => raw.any_number += 1,
                "exec" => raw.execs += 1,
                other => raw.problems.push(format!(
                    "{shown}, line {}: unknown profile directive {other}.",
                    child.line
                )),
            }
        }
        self.blocks.push(raw);
    }

    /// Resolves aliases and global defaults, as kanshi's `resolve_output_defaults` does.
    fn finish(self) -> Config {
        let mut anonymous = 0;
        let mut profiles = Vec::new();
        for raw in self.blocks {
            let mut warnings = self.problems.clone();
            warnings.extend(raw.problems);
            let mut entries = Vec::new();
            let mut outputs = Vec::new();
            for (mut settings, written) in raw.outputs {
                if settings.criteria.starts_with('$') {
                    match self
                        .defaults
                        .iter()
                        .find(|d| d.alias.as_ref() == Some(&settings.criteria))
                    {
                        Some(d) => settings.criteria.clone_from(&d.criteria),
                        None => warnings
                            .push(format!("The alias {} is not defined.", settings.criteria)),
                    }
                }
                if let Some(d) = self
                    .defaults
                    .iter()
                    .find(|d| d.criteria == settings.criteria)
                {
                    settings.fill_from(d);
                }
                entries.push(settings.entry());
                outputs.push(written);
            }
            if raw.execs > 0 {
                warnings
                    .push("kanshi runs this profile's exec commands; outlay does not.".to_owned());
            }
            if raw.any_number > 0 {
                warnings.push("outlay leaves ...output entries to kanshi.".to_owned());
            }
            let name = raw.name.unwrap_or_else(|| {
                anonymous += 1;
                format!("<anonymous profile {anonymous}>")
            });
            let d = raw.directive;
            profiles.push(Block {
                anonymous: d.params.is_empty(),
                name,
                file: raw.file,
                lines: d.lines.clone(),
                start: d.start,
                open: d.open.unwrap_or(d.lines.end),
                profile: Profile {
                    entries,
                    primary: None,
                    warnings,
                },
                outputs,
            });
        }
        Config {
            profiles,
            files: self.files,
            problems: self.problems,
        }
    }
}

/// Reads a kanshi config from its text, as if it were the file at `path`; includes are read
/// from the disk.
pub fn parse(path: &Path, text: &str) -> Config {
    let mut reader = Reader::default();
    reader.file(path.to_owned(), text.to_owned(), 0);
    reader.finish()
}

/// Reads the kanshi config at `path` and the files it includes.
pub fn read(path: &Path) -> io::Result<Config> {
    let text = std::fs::read_to_string(path)?;
    Ok(parse(path, &text))
}

impl Config {
    /// The first profile with this name: the one kanshi's `kanshictl switch` would pick.
    pub fn find(&self, name: &str) -> Option<&Block> {
        self.profiles.iter().find(|b| b.name == name)
    }
}

// --- Writing ------------------------------------------------------------------------------------

/// The `# generated by outlay` line above a block outlay wrote.
pub fn header() -> String {
    format!("# generated by outlay {}", env!("CARGO_PKG_VERSION"))
}

fn is_header(line: &str) -> bool {
    line.trim().starts_with("# generated by outlay")
}

/// The connected outputs a block lists, in display-number order.
fn heads(snap: &Snapshot) -> Vec<usize> {
    snap.numbered()
        .into_iter()
        .filter(|&i| snap.outputs[i].is_connected())
        .collect()
}

/// A glob that matches exactly `text`.
fn glob_escape(text: &str) -> String {
    let mut out = String::new();
    for c in text.chars() {
        if matches!(c, '*' | '?' | '[' | '\\') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// The criteria for an output a block did not name yet: the name for a built-in panel and for
/// a display that does not report its make, model and serial, or shares them with another one;
/// else its description, which stays the same on any connector.
fn criteria_for(snap: &Snapshot, i: usize) -> String {
    let out = &snap.outputs[i];
    let complete = out.identity.as_ref().is_some_and(|id| {
        [&id.make, &id.model, &id.serial]
            .iter()
            .all(|f| f.as_deref().is_some_and(|v| !v.is_empty()))
    });
    let desc = description(out);
    let unique = heads(snap)
        .into_iter()
        .filter(|&j| description(&snap.outputs[j]) == desc)
        .count()
        == 1;
    if built_in(&out.name) || !complete || !unique {
        out.name.clone()
    } else {
        glob_escape(&desc)
    }
}

/// `60`, `143.912`: a rate in mHz as kanshi reads it, with no trailing zeros.
fn rate_text(millihertz: u32) -> String {
    let text = format!("{:.3}", f64::from(millihertz) / 1000.0);
    text.trim_end_matches('0').trim_end_matches('.').to_owned()
}

/// The `output` line for output `i` of `layout`.
fn output_line(criteria: &str, layout: &Layout, i: usize, adaptive_sync: Option<bool>) -> String {
    let st = &layout.outputs[i];
    let criteria = quote(criteria);
    let Some(mode) = st.mode.as_ref().filter(|_| st.enabled) else {
        return format!("output {criteria} disable");
    };
    let millihertz = mode_millihertz(mode);
    let rate = if millihertz == 0 {
        String::new()
    } else {
        format!("@{}Hz", rate_text(millihertz))
    };
    let custom = if mode.custom { "--custom " } else { "" };
    let mut line = format!(
        "output {criteria} enable mode {custom}{}x{}{rate} position {},{} scale {} transform {}",
        mode.width,
        mode.height,
        st.pos.x,
        st.pos.y,
        st.scaling.factor().unwrap_or(1.0),
        transform_name(st.rotation, st.reflection),
    );
    if let Some(on) = adaptive_sync {
        line.push_str(if on {
            " adaptive_sync on"
        } else {
            " adaptive_sync off"
        });
    }
    line
}

/// Where a directive's text goes when it is removed: its whole lines when nothing else shares
/// them.
fn removal(text: &str, lines: &Range<usize>, start: usize) -> Range<usize> {
    if text[lines.start..start].trim().is_empty() {
        lines.clone()
    } else {
        start..lines.end
    }
}

/// A new block for `layout`, every connected output on its own line.
fn new_block(name: &str, layout: &Layout, snap: &Snapshot) -> String {
    let mut block = format!("{}\nprofile {} {{\n", header(), quote(name));
    for i in heads(snap) {
        block.push_str(INDENT);
        block.push_str(&output_line(&criteria_for(snap, i), layout, i, None));
        block.push('\n');
    }
    block.push_str("}\n");
    block
}

/// `text` with `block` rewritten for `layout`: each `output` directive that still matches a
/// connected output gets that output's settings under the criteria the user wrote, the others
/// go, outputs no directive matched are added after the last one, and the `# generated by
/// outlay` line above the block is added or updated. Everything else stays.
fn rewrite(text: &str, block: &Block, layout: &Layout, snap: &Snapshot) -> String {
    let heads = heads(snap);
    let found = block.profile.matches(snap);
    let mut edits: Vec<(Range<usize>, String)> = Vec::new();
    let mut done: Vec<usize> = Vec::new();
    for (w, found) in block.outputs.iter().zip(found) {
        match found.filter(|i| heads.contains(i) && !done.contains(i)) {
            Some(i) => {
                let line = output_line(&w.criteria, layout, i, w.adaptive_sync);
                edits.push((w.start..w.lines.end, format!("{line}\n")));
                done.push(i);
            }
            None => edits.push((removal(text, &w.lines, w.start), String::new())),
        }
    }
    let indent = block
        .outputs
        .first()
        .map(|w| &text[w.lines.start..w.start])
        .filter(|prefix| prefix.trim().is_empty())
        .unwrap_or(INDENT);
    let added: String = heads
        .iter()
        .filter(|i| !done.contains(i))
        .map(|&i| {
            format!(
                "{indent}{}\n",
                output_line(&criteria_for(snap, i), layout, i, None)
            )
        })
        .collect();
    if !added.is_empty() {
        let at = match block.outputs.last() {
            Some(w) => w.lines.end,
            // Right after the line that opens the block.
            None => text[block.open..]
                .find('\n')
                .map_or(text.len(), |k| block.open + k + 1),
        };
        let lead = if text[..at].ends_with('\n') { "" } else { "\n" };
        edits.push((at..at, format!("{lead}{added}")));
    }
    let own_indent = &text[block.lines.start..block.start];
    let own_indent = if own_indent.trim().is_empty() {
        own_indent
    } else {
        ""
    };
    let above = text[..block.lines.start.saturating_sub(1)]
        .rfind('\n')
        .map_or(0, |k| k + 1);
    let header = format!("{own_indent}{}\n", header());
    if block.lines.start > 0 && is_header(&text[above..block.lines.start]) {
        edits.push((above..block.lines.start, header));
    } else {
        edits.push((block.lines.start..block.lines.start, header));
    }
    // From the end, so earlier ranges stay where they are; at one place, the later edit first.
    let mut out = text.to_owned();
    edits.sort_by_key(|(r, _)| std::cmp::Reverse((r.start, r.end)));
    for (range, with) in edits {
        out.replace_range(range, &with);
    }
    out
}

/// What saving `layout` as profile `name` writes: the file and its new text. The block that has
/// that name is rewritten in the file that holds it; a new one goes at the end of the config at
/// `main`. `config` is `None` when there is no config yet.
pub fn save(
    config: Option<&Config>,
    main: &Path,
    name: &str,
    layout: &Layout,
    snap: &Snapshot,
) -> (PathBuf, String) {
    if let Some((config, block)) = config.and_then(|c| Some((c, c.find(name)?))) {
        let (path, text) = &config.files[block.file];
        return (path.clone(), rewrite(text, block, layout, snap));
    }
    let mut text = config
        .and_then(|c| c.files.first())
        .map(|(_, t)| t.clone())
        .unwrap_or_default();
    if !text.is_empty() {
        if !text.ends_with('\n') {
            text.push('\n');
        }
        if !text.ends_with("\n\n") {
            text.push('\n');
        }
    }
    text.push_str(&new_block(name, layout, snap));
    (main.to_owned(), text)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn directives(text: &str) -> (Vec<Directive>, Vec<String>) {
        let mut p = Parser::new(text);
        let d = p.block(false);
        (d, p.problems)
    }

    #[test]
    fn reads_scfg_as_libscfg_does() {
        let text = "# top\nprofile \"my desk\" {\n\toutput 'A B' enable\n\toutput \"x\\\"y\" {\n\t\tmode 1x1\n\t}\n}\ninclude a\\ b\n";
        let (d, problems) = directives(text);
        assert!(problems.is_empty(), "{problems:?}");
        assert_eq!(d.len(), 2);
        assert_eq!(d[0].name, "profile");
        assert_eq!(d[0].params, ["my desk"]);
        let children = d[0].children.as_ref().unwrap();
        assert_eq!(children[0].params, ["A B", "enable"]);
        assert_eq!(children[1].params, ["x\"y"]);
        assert_eq!(children[1].children.as_ref().unwrap()[0].params, ["1x1"]);
        assert_eq!(d[1].params, ["a b"]);
        assert_eq!(
            &text[d[0].lines.clone()],
            &text[6..text.find("include").unwrap()]
        );
        assert_eq!(&text[children[0].lines.clone()], "\toutput 'A B' enable\n");
        assert_eq!(
            &text[children[1].lines.clone()],
            "\toutput \"x\\\"y\" {\n\t\tmode 1x1\n\t}\n"
        );
        assert_eq!(d[1].line, 8);
    }

    #[test]
    fn a_hash_inside_a_line_is_a_word() {
        let (d, _) = directives("output A enable # not a comment\n");
        assert_eq!(d[0].params, ["A", "enable", "#", "not", "a", "comment"]);
    }

    #[test]
    fn syntax_problems_are_reported_and_reading_goes_on() {
        let (d, problems) = directives("profile x {\n output \"A enable\n}\n}\nprofile y {\n");
        assert_eq!(d.len(), 2);
        assert_eq!(
            problems,
            [
                "line 2: a quoted word is not closed",
                "line 4: unexpected '}'",
                "line 6: a block has no closing '}'"
            ]
        );
    }

    #[test]
    fn quotes_only_what_needs_it() {
        assert_eq!(quote("eDP-1"), "eDP-1");
        assert_eq!(quote("$dell"), "$dell");
        assert_eq!(quote("Dell Inc. U2719D 7LQ"), "\"Dell Inc. U2719D 7LQ\"");
        assert_eq!(quote("a\"b\\c"), "\"a\\\"b\\\\c\"");
        assert_eq!(quote(""), "\"\"");
        for word in ["eDP-1", "Dell Inc. X 1", "a\"b\\c", "x{y}", "#1", ""] {
            let (d, _) = directives(&format!("output {}\n", quote(word)));
            assert_eq!(d[0].params, [word], "{word:?}");
        }
    }

    #[test]
    fn modes_as_kanshi_reads_them() {
        assert_eq!(parse_mode("1920x1080"), Some((1920, 1080, None)));
        assert_eq!(parse_mode("1920x1080@60"), Some((1920, 1080, Some(60.0))));
        assert_eq!(
            parse_mode("2560x1440@143.912Hz"),
            Some((2560, 1440, Some(143.912)))
        );
        assert_eq!(parse_mode("1280x720@0"), Some((1280, 720, None)));
        assert_eq!(parse_mode("1920"), None);
        assert_eq!(parse_mode("1920x1080@fast"), None);
        assert_eq!(rate_text(60_000), "60");
        assert_eq!(rate_text(143_912), "143.912");
        assert_eq!(rate_text(59_940), "59.94");
    }

    #[test]
    fn includes_expand_home_variables_and_globs() {
        let dir = std::env::temp_dir().join(format!("outlay-kanshi-expand-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("conf.d")).unwrap();
        for name in ["b", "a", ".hidden"] {
            std::fs::write(dir.join("conf.d").join(name), "").unwrap();
        }
        let from = dir.join("config");
        let home = Path::new("/home/me");
        assert_eq!(
            expand("~/k/config", &from, Some(home)).unwrap(),
            [PathBuf::from("/home/me/k/config")]
        );
        assert_eq!(
            expand("conf.d/*", &from, Some(home)).unwrap(),
            [dir.join("conf.d/a"), dir.join("conf.d/b")]
        );
        assert_eq!(
            expand("conf.d/none-*", &from, Some(home)).unwrap(),
            [dir.join("conf.d/none-*")],
            "no match: the pattern itself, as wordexp leaves it"
        );
        let err = expand("$OUTLAY_TEST_SURELY_UNSET/x", &from, Some(home)).unwrap_err();
        assert!(err.contains("not set"), "{err}");
        std::fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn criteria_become_targets() {
        let config = parse(
            Path::new("/k/config"),
            "profile p {\n output eDP-1\n output \"Dell Inc. DELL U2719D 7LQ2M43\"\n output \"Dell*\"\n output *\n}\n",
        );
        let targets: Vec<Target> = config.profiles[0]
            .profile
            .entries
            .iter()
            .map(|e| e.target.clone())
            .collect();
        assert_eq!(
            targets,
            [
                Target::Name("eDP-1".to_owned()),
                Target::Description("Dell Inc. DELL U2719D 7LQ2M43".to_owned()),
                Target::Description("Dell*".to_owned()),
                Target::Any,
            ]
        );
    }
}
